// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.Models
{
    public partial class UserAction
    {
        public decimal Id { get; set; }
        public decimal UserId { get; set; }
        public DateTime DisplayDate { get; set; }
    }
}