// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Evse.DTO
{
    public partial class PrivacyPolicyDto
    {
        public decimal Id { get; set; }
        public string PrivacyDescript { get; set; }
        public string Comment { get; set; }
        public DateTime? CreateDate { get; set; }
        public decimal? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public decimal? UpdateBy { get; set; }
        public string Status { get; set; }
        public string StatusName { get; set; }
        public string Guid { get; set; }
    }
}